name: Build with Gradle

on:
  push:
    branches: ["**"]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Unit Test Results (Checks)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: "**/build/test-results/test/*.xml"
          reporter: java-junit
          fail-on-error: false

      - name: Upload HTML Test Reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-html
          path: |
            **/build/reports/tests/test/**
            build/reports/tests/test/**
          if-no-files-found: ignore
          retention-days: 7
